// Generated by CoffeeScript 1.6.3
var Alien, AlienManager, AlienShot, HEIGHT, SHIP_POSY, Ship, ShipShot, WIDTH, alienCallback, alienCallbackRate, alienId, alienShot, alienSteps, alienStepsDown, aliens, aliensDelta, aliensFireRate, am, gameOver, ship, shipCallback, shipShot, shotCallback;

WIDTH = 800;

HEIGHT = 600;

SHIP_POSY = HEIGHT - 60;

ShipShot = (function() {
  ShipShot.prototype.width = 2;

  ShipShot.prototype.height = 20;

  ShipShot.prototype.elem = function() {
    return $('#ship-shot');
  };

  function ShipShot(posx) {
    this.posx = posx;
    this.posy = SHIP_POSY;
    $.playground().addSprite('ship-shot', {
      posx: this.posx,
      posy: this.posy,
      width: this.width,
      height: this.height,
      animation: new $.gQ.Animation({
        imageURL: "images/ship-shot.jpg"
      })
    });
  }

  ShipShot.prototype.updatePos = function() {
    if (this.posy > 0) {
      this.posy -= 20;
      this.elem().y(this.posy);
      return this;
    } else {
      return this.destroy();
    }
  };

  ShipShot.prototype.destroy = function() {
    this.elem().remove();
    return null;
  };

  ShipShot.prototype.rect = function() {
    return {
      top: this.posy,
      left: this.posx,
      bottom: this.posy + this.height,
      right: this.posx + this.width
    };
  };

  return ShipShot;

})();

AlienShot = (function() {
  AlienShot.prototype.width = 2;

  AlienShot.prototype.height = 20;

  AlienShot.prototype.elem = function() {
    return $('#alien-shot');
  };

  function AlienShot(posx, posy) {
    this.posx = posx;
    this.posy = posy;
    $.playground().addSprite('alien-shot', {
      posx: this.posx,
      posy: this.posy,
      width: this.width,
      height: this.height,
      animation: new $.gQ.Animation({
        imageURL: "images/ship-shot.jpg"
      })
    });
  }

  AlienShot.prototype.updatePos = function() {
    if (this.posy < HEIGHT) {
      this.posy += 10;
      this.elem().y(this.posy);
      return this;
    } else {
      return this.destroy();
    }
  };

  AlienShot.prototype.destroy = function() {
    this.elem().remove();
    return null;
  };

  AlienShot.prototype.rect = function() {
    return {
      top: this.posy,
      left: this.posx,
      bottom: this.posy + this.height,
      right: this.posx + this.width
    };
  };

  return AlienShot;

})();

Ship = (function() {
  function Ship(args) {}

  Ship.prototype.posx = 0;

  Ship.prototype.width = 63;

  Ship.prototype.height = 40;

  Ship.prototype.elem = function() {
    return $('#ship');
  };

  Ship.prototype.animation = function() {
    return new $.gQ.Animation({
      imageURL: "images/space-invaders-ship1.jpg"
    });
  };

  Ship.prototype.spriteData = function() {
    return {
      posx: this.posx,
      posy: SHIP_POSY,
      height: this.height,
      width: this.width,
      animation: this.animation()
    };
  };

  Ship.prototype.moveRight = function() {
    if (this.posx < WIDTH) {
      this.posx += 5;
    }
    return this.updatePos();
  };

  Ship.prototype.moveLeft = function() {
    if (this.posx > 0) {
      this.posx -= 5;
    }
    return this.updatePos();
  };

  Ship.prototype.updatePos = function() {
    return this.elem().x(this.posx);
  };

  Ship.prototype.fire = function() {
    return new ShipShot(this.posx + this.width / 2);
  };

  Ship.prototype.collidesWith = function(rect) {
    return SHIP_POSY <= rect.bottom && SHIP_POSY + this.height >= rect.top && this.posx <= rect.right && this.posx + this.width >= rect.left;
  };

  return Ship;

})();

alienId = 0;

Alien = (function() {
  Alien.prototype.width = 40;

  Alien.prototype.height = 30;

  function Alien(posx, posy, type) {
    var rate;
    this.posx = posx;
    this.posy = posy;
    this.type = type;
    this.id = (alienId += 1);
    rate = 100 + 200 * Math.random();
    $.playground().addSprite("alien-" + this.id, {
      posx: this.posx,
      posy: this.posy,
      width: this.width,
      height: this.height,
      animation: new $.gQ.Animation({
        imageURL: "images/invader" + this.type + ".jpg",
        numberOfFrame: 4,
        delta: 30,
        rate: rate,
        type: $.gameQuery.ANIMATION_VERTICAL
      })
    });
  }

  Alien.prototype.elem = function() {
    return $("#alien-" + this.id);
  };

  Alien.prototype.moveHoriz = function(deltax) {
    this.posx += deltax;
    return this.updatePos();
  };

  Alien.prototype.moveVert = function(deltay) {
    this.posy += deltay;
    return this.updatePos();
  };

  Alien.prototype.updatePos = function() {
    return this.elem().x(this.posx).y(this.posy);
  };

  Alien.prototype.collidesWith = function(rect) {
    return this.posy <= rect.bottom && this.posy + this.height >= rect.top && this.posx <= rect.right && this.posx + this.width >= rect.left;
  };

  Alien.prototype.destroy = function() {
    return this.elem().fadeOut(500, function() {
      return this.elem().remove();
    });
  };

  Alien.prototype.fire = function() {
    return new AlienShot(this.posx + this.width / 2, this.posy + this.height);
  };

  return Alien;

})();

aliens = [];

AlienManager = (function() {
  function AlienManager() {}

  AlienManager.prototype.type = 0;

  AlienManager.prototype.generujRzadekAlienow = function(num) {
    var x, _i, _results;
    this.type += 1;
    _results = [];
    for (x = _i = 0; _i <= 9; x = ++_i) {
      _results.push(aliens.push(new Alien(20 + x * 60, 20 + num * 40, this.type % 3)));
    }
    return _results;
  };

  AlienManager.prototype.destroy = function(a) {
    a.destroy();
    return aliens.splice(aliens.indexOf(a), 1);
  };

  return AlienManager;

})();

am = new AlienManager;

ship = new Ship;

shipShot = null;

shipCallback = function() {
  if ($.gameQuery.keyTracker[37]) {
    ship.moveLeft();
  }
  if ($.gameQuery.keyTracker[39]) {
    ship.moveRight();
  }
  if ($.gameQuery.keyTracker[32]) {
    if (!shipShot) {
      return shipShot = ship.fire();
    }
  }
};

alienShot = null;

shotCallback = function() {
  var alien, _i, _len;
  if (shipShot) {
    shipShot = shipShot.updatePos();
    for (_i = 0, _len = aliens.length; _i < _len; _i++) {
      alien = aliens[_i];
      if (alien.collidesWith(shipShot.rect())) {
        am.destroy(alien);
        shipShot = shipShot.destroy();
        break;
      }
    }
  }
  if (alienShot) {
    alienShot = alienShot.updatePos();
    if (alienShot && ship.collidesWith(alienShot.rect())) {
      return gameOver();
    }
  }
};

gameOver = function() {
  $.playground().pauseGame();
  return $('#game-over-screen').fadeIn(2000);
};

aliensDelta = 5;

alienSteps = 0;

alienStepsDown = 0;

aliensFireRate = 0.01;

alienCallbackRate = 150;

alienCallback = function() {
  var alien, _i, _j, _len, _len1;
  for (_i = 0, _len = aliens.length; _i < _len; _i++) {
    alien = aliens[_i];
    alien.moveHoriz(aliensDelta);
    if (!alienShot && Math.random() < aliensFireRate) {
      alienShot = alien.fire();
    }
  }
  alienSteps += 1;
  if (alienSteps >= 30) {
    alienSteps = 0;
    aliensDelta = -aliensDelta;
    for (_j = 0, _len1 = aliens.length; _j < _len1; _j++) {
      alien = aliens[_j];
      alien.moveVert(10);
      if (alien.posy >= SHIP_POSY) {
        gameOver();
      }
    }
    alienStepsDown += 1;
    if (alienStepsDown > 3) {
      alienStepsDown = 0;
      aliensDelta += 1;
      am.generujRzadekAlienow(0);
      aliensFireRate *= 1.1;
      return alienCallbackRate -= 10;
    }
  }
};

$(function() {
  $("#startbutton").click(function() {
    return $.playground().startGame(function() {
      return $("#welcomeScreen").remove();
    });
  });
  $('#playground').playground({
    height: HEIGHT,
    width: WIDTH,
    keyTracker: true
  });
  $.playground().addSprite('ship', ship.spriteData());
  am.generujRzadekAlienow(5);
  am.generujRzadekAlienow(4);
  am.generujRzadekAlienow(3);
  am.generujRzadekAlienow(2);
  am.generujRzadekAlienow(1);
  am.generujRzadekAlienow(0);
  $.playground().registerCallback(shipCallback, 15);
  $.playground().registerCallback(shotCallback, 10);
  return $.playground().registerCallback(alienCallback, alienCallbackRate);
});
